title: SmartDrivingCar
description: The latest news in mobility and autonomy
baseurl: "/smartdrivingcar" # repo name for organization project site
url: "https://princetonuniversity.github.io" # org GitHub Pages root
permalink: pretty
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
collections:
  pages:
    output: true
  newsletters:
    output: true
    permalink: /newsletter/:year/:month/:day/:slug/
defaults:
  - scope:
      path: ""
      type: "newsletters"
    values:
      layout: newsletter
sass:
  style: compressed
exclude:
  - node_modules
  - Gemfile*
  - vendor
  - scripts
