title: SmartDrivingCar
description: The latest news in mobility and autonomy
# Base (production/local) config keeps baseurl empty so links are root-relative under custom domain or local dev.
baseurl: "" # empty for prod & local
url: "https://smartdrivingcar.com" # production custom domain (overridden in preview & local as needed)
permalink: pretty
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
collections:
  pages:
    output: true
  newsletters:
    output: true
    permalink: /newsletter/:year/:month/:day/:slug/
defaults:
  - scope:
      path: ""
      type: "newsletters"
    values:
      layout: newsletter
sass:
  style: compressed
exclude:
  - node_modules
  - Gemfile*
  - vendor
  - scripts
